# -*- coding: utf-8 -*-
"""Purple Merit_ASSESSMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xWIsJ_35gYTEzTo_LEQXPTKhPQkQuZtR

#  DATA CLEANING & PREPARATION  And EDA of Urban Threads
"""

# 1. Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 2. Load Dataset
df = pd.read_csv(r"/content/urbanthreads_q4.csv")

# 3. Basic Info
print("Initial Dataset Shape:", df.shape)
print("\nData Types:\n", df.dtypes)
print("\n1st 5 rows of dataset:\n",df.head())
print("\nlast 5 rows of dataset:\n",df.tail())
print("\nbasic info of dataset:\n",df.info())
print("\nStatistics of dataset:\n",df.describe(include="all"))

# 4. Type Casting
df['Order Date'] = pd.to_datetime(df['Order Date'],errors='coerce')
df['Del Date'] = pd.to_datetime(df['Del Date'],errors='coerce')
df['Ret Rec'] = pd.to_datetime(df['Ret Rec'],errors='coerce')
print("\nData Types:\n",df.dtypes)

# 5. Separate Numerical & Categorical Columns
# Numerical columns
numerical_columns = df.select_dtypes(include=np.number).columns.tolist()
# Categorical columns (only object or category types)
categorical_columns = df.select_dtypes(include=["object", "category"]).columns.tolist()
# Datetime columns
datetime_columns = df.select_dtypes(include=["datetime64[ns]", "datetimetz"]).columns.tolist()

print("Numerical:", numerical_columns)

print("Categorical:", categorical_columns)

print("Datetime:", datetime_columns)

# 6. Handling Duplicate
df.duplicated().sum()

# 7. Handling Missing Values
df.isnull().sum()

df['Discount Code'] = df['Discount Code'].fillna('No Discount')
df['Reason'] = df['Reason'].fillna('Not Returned')

df.isnull().sum()

# 8. OutlierDetection
for i, col in enumerate(numerical_columns):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    outliers = df[(df[col] < (Q1 - 1.5 * IQR)) | (df[col] > (Q3 + 1.5 * IQR))]
    print(f"Outliers detected in {col}:\n", outliers[col])
    plt.figure(figsize=(6,4))
    sns.boxplot(y=df[col])
    plt.title(f"Boxplot of {col}")
    plt.show()

for i, col in enumerate(datetime_columns):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    outliers = df[(df[col] < (Q1 - 1.5 * IQR)) | (df[col] > (Q3 + 1.5 * IQR))]
    print(f"Outliers detected in {col}:\n", outliers[col])
    plt.figure(figsize=(6,4))
    sns.boxplot(y=df[col])
    plt.title(f"Boxplot of {col}")
    plt.show()

# 9. Final check
df.info()

# EDA
df_EDA = df.copy()

# 10. First Moment Business Decision / Measures of Central Tendency
# mean
mean = df_EDA[numerical_columns].mean()
print(mean)

# median
median = df_EDA[numerical_columns].median()
print(median)

# mode
mode = df_EDA[numerical_columns].mode()
print(mode)

mode2 = df_EDA[categorical_columns].mode()
print(mode2)

# 11. Second Moment Business Decision / Measures of Dispersion
# Standard Deviation
Standard_Deviation = df_EDA[numerical_columns].std()
print(Standard_Deviation)

#  Variance
Variance = df_EDA[numerical_columns].var()
print(Variance)

# Range
Range = df_EDA[numerical_columns].max() - df_EDA[numerical_columns].min()
print(Range)

# 12. Third Moment Business Decision / Skewness
# skewness
skewness = df_EDA[numerical_columns].skew()
print(skewness)

# 13. Fourth Moment Business Decision / Kurtosis
# Kurtosis
Kurtosis = df_EDA[numerical_columns].kurtosis()
print(Kurtosis)

# 14.  Correlation Analysis
corr_matrix = df_EDA[numerical_columns].corr()
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

# 15. Univariate Analysis
# Set style
sns.set(style="whitegrid")
# Number of rows needed for subplots (2 columns layout)
n_rows = (len(numerical_columns) + 1) // 2
# Create subplots
fig, axes = plt.subplots(n_rows, 2, figsize=(12, n_rows * 4))
axes = axes.flatten()  # Flatten to 1D array for easy iteration
# Loop through numeric columns
for i, col in enumerate(numerical_columns):
    sns.histplot(df_EDA[col], kde=True, ax=axes[i], bins=30, color="skyblue")
    axes[i].set_title(f"Histogram & KDE of {col}", fontsize=12)
    axes[i].set_xlabel(col, fontsize=10)
    axes[i].set_ylabel("Frequency")
# Remove unused subplot axes if any
for j in range(i+1, len(axes)):
    fig.delaxes(axes[j])
plt.tight_layout()
plt.show()

# 16. Bivariate / Multivariate Analysis
df_EDA['Delivery_Days'] = (df_EDA['Del Date'] - df_EDA['Order Date']).dt.days
#Scatterplots
#Delivery Time vs Order Value
plt.figure()
plt.scatter(df_EDA['Delivery_Days'], df_EDA['Total'])
plt.xlabel('Delivery Days')
plt.ylabel('Order Value')
plt.title('Delivery Time vs Order Value')
plt.show()

#Discount % vs Order Value
plt.figure()
plt.scatter(df_EDA['Disc %'], df_EDA['Total'])
plt.xlabel('Discount Percentage')
plt.ylabel('Order Value')
plt.title('Discount % vs Order Value')
plt.show()

#Quantity vs Order Value
plt.figure()
plt.scatter(df_EDA['Qty'], df_EDA['Total'])
plt.xlabel('Quantity')
plt.ylabel('Order Value')
plt.title('Quantity vs Order Value')
plt.show()

#pair plot
sns.pairplot(df_EDA[numerical_columns], diag_kind="kde", plot_kws={'alpha':0.5})
plt.suptitle("Pairplot of Numerical Variables", y=1.02)
plt.show()

# 17. Export Clean Dataset
import os
output_file = "Urban ThreadsData_Clean.csv"
df.to_csv(output_file, index=False)
print("Final clean dataset saved at:")
print(os.path.abspath(output_file))